import {
  Device,
  DeviceEvent,
  B2BAccount,
  B2BContact,
  Opportunity,
  B2BQuote,
  ITADBatch,
  Order,
  WarrantyClaim,
  RMAInspection,
  InventoryMovement,
} from '@/types/wathiq';

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'WTH-26-LPT-000184',
    sku: 'LEN-T14-G2-I5-16-512',
    category: 'Laptop',
    brand: 'Lenovo',
    manufacturer: 'Lenovo Group Ltd',
    model: 'ThinkPad T14 Gen 2',
    modelNumber: '20W0004NUS',
    serialNumber: 'PF-2947A890',
    macAddress: '3C:52:82:11:9A:F0',
    specs: {
      cpu: 'Intel Core i5-1145G7 (4C/8T, 2.6/4.4GHz)',
      ram: '16GB DDR4-3200MHz',
      storage: '512GB NVMe PCIe 3.0 M.2 SSD',
      display: '14" FHD (1920x1080) IPS 300nits Anti-glare',
      gpu: 'Intel Iris Xe Graphics',
      color: 'Black Matte Soft-Touch',
      os: 'Windows 11 Pro 64-bit (Activated OEM)',
    },
    batteryHealth: 91,
    batteryCycles: 142,
    ssdHealth: 98,
    acquisitionSource: 'ITAD Corporate Buyback - Bank of Africa Casablanca',
    acquisitionDate: '2026-08-12',
    costs: {
      acquisitionCost: 3200,
      transport: 120,
      customs: 0,
      certification: 150,
      parts: 450,
      labor: 280,
      packaging: 65,
      otherDirect: 40,
      landedCost: 4305,
      warrantyReserve: 215,
      paymentFees: 60,
      shippingSubsidy: 50,
      expectedReturns: 80,
      contributionMargin: 1190,
    },
    pricing: {
      minimumPrice: 4800,
      recommendedPrice: 5900,
      marketPrice: 6500,
      sellingPrice: 5900,
      currency: 'MAD',
      targetMarginPct: 27.0,
    },
    valuation: {
      acquisitionValue: 3200,
      landedCost: 4305,
      marketValue: 6500,
      tradeInValue: 3400,
      wholesaleValue: 4900,
      recommendedRetailPrice: 5900,
      expectedResidualValue12m: 3800,
      valuationBasis: 'Grade A rating, genuine 91% battery, high B2B call center demand index.',
      currency: 'MAD',
      updatedAt: '2026-08-16 17:00:00',
    },
    provenance: {
      countryOfOrigin: 'China / Assembled for EMEA',
      importerIdentity: 'Lenovo Morocco SARL (ICE: 001492810000021)',
      customsDeclarationNumber: 'D10-CAS-2021-99418',
      importStatus: 'VERIFIED',
      anrtHomologationStatus: 'VERIFIED',
      blacklistStatus: 'NO_MATCH_FOUND',
      financingLienStatus: 'NO_MATCH_FOUND',
      ownershipChainStatus: 'VERIFIED',
      overallTrustStatus: 'WATHIQ_VERIFIED',
      checks: [
        {
          id: 'CHK-001',
          checkType: 'IDENTITY_OEM',
          label: 'OEM Serial & Component Consistency',
          sourceName: 'Lenovo Warranty & Parts Lookup API',
          sourceTrustLevel: 'OFFICIAL',
          sourceReference: 'LEN-SYS-PF2947A890',
          requestedAt: '2026-08-12 10:00:00',
          completedAt: '2026-08-12 10:00:05',
          status: 'VERIFIED',
          resultSummary: 'Motherboard serial matches original Lenovo factory manifest.',
          confidence: 1.0,
          operatorOrSystem: 'Lenovo API Gateway',
        },
        {
          id: 'CHK-002',
          checkType: 'IMPORT_CUSTOMS_DECLARATION',
          label: 'Customs Declaration Verification',
          sourceName: 'ADII BADR Customs Database',
          sourceTrustLevel: 'OFFICIAL',
          sourceReference: 'D10-CAS-2021-99418',
          requestedAt: '2026-08-12 10:05:00',
          completedAt: '2026-08-12 10:05:02',
          status: 'VERIFIED',
          resultSummary: 'Import documentation verified under Declaration D10-CAS-2021-99418 (Casablanca Port).',
          confidence: 1.0,
          operatorOrSystem: 'ADII Customs Bridge',
        },
        {
          id: 'CHK-003',
          checkType: 'OWNERSHIP_CHAIN_OF_CUSTODY',
          label: 'Corporate Ownership & Transfer of Custody',
          sourceName: 'Bank of Africa Asset Manifest',
          sourceTrustLevel: 'PARTNER',
          sourceReference: 'MNF-BOA-2026-089',
          requestedAt: '2026-08-12 10:10:00',
          completedAt: '2026-08-12 10:10:01',
          status: 'VERIFIED',
          resultSummary: 'Direct enterprise consignment from Bank of Africa CIO Office under legal ITAD contract.',
          confidence: 0.98,
          operatorOrSystem: 'Wathiq Logistics Bay',
        },
      ],
      documents: [
        {
          id: 'DOC-001',
          docType: 'ITAD_MANIFEST',
          title: 'Bank of Africa Collection Manifest MNF-BOA-2026-089',
          documentHash: '4f2898a12c8b091f63b519c2a49b6d8e7a1f0c2b3d4e5f6a7b8c9d0e1f2a3b4c',
          hashAlgorithm: 'SHA-256',
          storageRef: 's3://wathiq-docs/itad/2026/mnf-boa-089.pdf',
          issuedBy: 'Bank of Africa Head Office',
          issuedAt: '2026-08-10',
          sourceTrustLevel: 'PARTNER',
        },
      ],
      lastVerifiedAt: '2026-08-16 17:00:00',
    },
    grade: 'A',
    detailedGrading: {
      screen: 'A',
      body: 'B',
      keyboard: 'A',
      batteryScore: 'A',
      functionalScore: 'A',
      notes: 'Micro-scratches on bottom chassis; screen & keyboard pristine. 91% genuine battery.',
    },
    status: 'READY_FOR_SALE',
    location: {
      warehouse: 'Casablanca Central Hub',
      zone: 'Zone B - Finished Goods',
      shelf: 'Shelf 03',
      bin: 'Bin 14',
    },
    warranty: {
      durationMonths: 12,
      terms: '12 Months Express Replacement Hardware Warranty, Wathiq Morocco Care',
      certificateNumber: 'WTH-CERT-2026-08914',
    },
    diagnostics: {
      cpu: true,
      ram: true,
      ssd: true,
      gpu: true,
      display: true,
      keyboard: true,
      trackpad: true,
      webcam: true,
      mic: true,
      speakers: true,
      usb: true,
      hdmi: true,
      usbC: true,
      wifi: true,
      bluetooth: true,
      battery: true,
      thermals: true,
      operator: 'Tarik Bensouda (Senior HW Tech)',
      timestamp: '2026-08-14 10:45:00',
      overallPass: true,
      notes: 'Thermal paste refreshed with Arctic MX-4. CPU stress temp under 74C.',
    },
    dataWipe: {
      software: 'Blancco Drive Eraser',
      version: 'v6.15.2-PRO',
      method: 'NIST 800-88 Rev 1 Purge (Cryptographic Erase + Overwrite)',
      operator: 'Amina El Amrani (Security Analyst)',
      date: '2026-08-14 14:20:00',
      certificateRef: 'BLAN-WTH-2026-8914-NIST',
      result: 'PASSED',
      verificationHash: '9e107d9d372bb6826bd81d3542a419d6b7e562ef6d8a39a973d4d360de5690b2',
    },
    qaInspection: {
      inspector: 'Hamza Radi (Lead QA Officer)',
      date: '2026-08-16 16:30:00',
      overallResult: 'PASS',
      checklist: [
        { id: 'disp', name: 'Display No dead pixels / Backlight uniform', passed: true, critical: true },
        { id: 'keys', name: 'Keyboard 100% keys functional & illuminated', passed: true, critical: true },
        { id: 'bat', name: 'Battery Health >= 80% genuine capacity', passed: true, critical: true },
        { id: 'wipe', name: 'Data wipe certificate verified on server', passed: true, critical: true },
        { id: 'bios', name: 'BIOS password cleared & Secure Boot enabled', passed: true, critical: true },
        { id: 'port', name: 'All IO ports verified under load', passed: true, critical: false },
        { id: 'cosm', name: 'Cosmetic Grade A standards adhered', passed: true, critical: false },
      ],
      notes: 'Device passed all mandatory 17 QA points with zero deviations.',
    },
    repairs: [
      {
        ticketId: 'REP-26-0034',
        description: 'Installed new original FR/AR backlit keyboard due to worn spacebar',
        partsUsed: [
          {
            partId: 'PRT-KB-LEN-T14G2',
            partName: 'ThinkPad T14 Gen 2 FR/AR Backlit Keyboard',
            partNumber: '5N20V43789',
            cost: 450,
          },
        ],
        laborHours: 1.5,
        laborRatePerHour: 186.6,
        totalCost: 730,
        technician: 'Tarik Bensouda',
        date: '2026-08-15',
        status: 'COMPLETED',
      },
    ],
    photos: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    ],
    ownership: 'Wathiq 1P Inventory',
    compliance: {
      wipedNIST80088: true,
      ceMarked: true,
      eWasteCompliant: true,
    },
    createdAt: '2026-08-12 09:30:00',
    updatedAt: '2026-08-16 17:00:00',
  },
  {
    // =================================================================
    // ACCEPTANCE TEST 2 SMARTPHONE (§51)
    // =================================================================
    id: 'WTH-26-PHN-000184',
    sku: 'APL-IPH-14-128-BLK',
    category: 'Smartphone',
    brand: 'Apple',
    manufacturer: 'Apple Inc',
    model: 'iPhone 14 128GB',
    modelNumber: 'A2882',
    serialNumber: 'K489X20P1L',
    imei: '358941094892014',
    specs: {
      cpu: 'A15 Bionic (5-core GPU, 6-core CPU)',
      ram: '6GB LPDDR4X',
      storage: '128GB NVMe',
      display: '6.1" Super Retina XDR OLED (2532x1170) TrueTone',
      gpu: '5-Core Apple GPU',
      color: 'Midnight Black Ceramic Shield',
      os: 'iOS 18.2 Clean Reset & Activated',
    },
    batteryHealth: 92,
    batteryCycles: 184,
    ssdHealth: 99,
    acquisitionSource: 'Corporate ITAD Buyback - OCP Group Casablanca',
    acquisitionDate: '2026-08-16',
    costs: {
      acquisitionCost: 4200,
      transport: 60,
      customs: 0,
      certification: 120,
      parts: 0,
      labor: 100,
      packaging: 40,
      otherDirect: 20,
      landedCost: 4540,
      warrantyReserve: 230,
      paymentFees: 65,
      shippingSubsidy: 40,
      expectedReturns: 50,
      contributionMargin: 1375,
    },
    pricing: {
      minimumPrice: 5400,
      recommendedPrice: 6300,
      marketPrice: 6900,
      sellingPrice: 6300,
      currency: 'MAD',
      targetMarginPct: 27.9,
    },
    valuation: {
      acquisitionValue: 4200,
      landedCost: 4540,
      marketValue: 6900,
      tradeInValue: 4500,
      wholesaleValue: 5300,
      recommendedRetailPrice: 6300,
      expectedResidualValue12m: 4400,
      valuationBasis: 'High battery retention (92%), original OLED panel, verified Moroccan customs import documentation.',
      currency: 'MAD',
      updatedAt: '2026-08-18 11:45:00',
    },
    provenance: {
      countryOfOrigin: 'United States / EMEA Version',
      importerIdentity: 'Apple Distribution International / Uno.ma (Authorized Importer)',
      customsDeclarationNumber: 'D10-CAS-2023-44180',
      importStatus: 'VERIFIED',
      anrtHomologationStatus: 'VERIFIED',
      blacklistStatus: 'NO_MATCH_FOUND',
      financingLienStatus: 'NO_MATCH_FOUND',
      ownershipChainStatus: 'VERIFIED',
      overallTrustStatus: 'WATHIQ_VERIFIED',
      checks: [
        {
          id: 'CHK-PHN-01',
          checkType: 'IDENTITY_OEM',
          label: 'Apple GSX Serial & Activation Lock Status',
          sourceName: 'Apple GSX Authoritative Gateway',
          sourceTrustLevel: 'OFFICIAL',
          sourceReference: 'GSX-ACT-CLR-9284',
          requestedAt: '2026-08-16 15:40:00',
          completedAt: '2026-08-16 15:40:03',
          status: 'VERIFIED',
          resultSummary: 'Find My iPhone OFF, iCloud Activation Lock cleared, MDM unenrollment verified.',
          confidence: 1.0,
          operatorOrSystem: 'Apple GSX API',
        },
        {
          id: 'CHK-PHN-02',
          checkType: 'IMEI_BLACKLIST',
          label: 'GSMA Device Check / International Blacklist',
          sourceName: 'GSMA Device Check & Moroccan Operator Registry',
          sourceTrustLevel: 'AUTHORIZED',
          sourceReference: 'GSMA-CLR-4892014',
          requestedAt: '2026-08-16 15:42:00',
          completedAt: '2026-08-16 15:42:02',
          status: 'NO_MATCH_FOUND',
          // Strict adherence to §2:
          resultSummary: 'No blacklist match found in the available authoritative data sources as of 2026-08-16.',
          confidence: 0.96,
          operatorOrSystem: 'GSMA Global Registry',
        },
        {
          id: 'CHK-PHN-03',
          checkType: 'IMPORT_CUSTOMS_DECLARATION',
          label: 'Moroccan Douanes Clearance Declaration',
          sourceName: 'Administration des Douanes et Impôts Indirects (ADII)',
          sourceTrustLevel: 'OFFICIAL',
          sourceReference: 'D10-CAS-2023-44180',
          requestedAt: '2026-08-16 15:45:00',
          completedAt: '2026-08-16 15:45:02',
          status: 'VERIFIED',
          resultSummary: 'Import documentation verified under Declaration D10-CAS-2023-44180.',
          confidence: 1.0,
          operatorOrSystem: 'ADII BADR Gateway',
        },
        {
          id: 'CHK-PHN-04',
          checkType: 'ANRT_HOMOLOGATION',
          label: 'ANRT Telecom Regulatory Homologation',
          sourceName: 'ANRT Moroccan Homologation Portal',
          sourceTrustLevel: 'OFFICIAL',
          sourceReference: 'ANRT-MR-2022-AP2882',
          requestedAt: '2026-08-16 15:47:00',
          completedAt: '2026-08-16 15:47:01',
          status: 'VERIFIED',
          resultSummary: 'Model A2882 holds active ANRT certificate for Maroc Telecom, Inwi, and Orange MA 4G/5G networks.',
          confidence: 1.0,
          operatorOrSystem: 'ANRT Verification Bridge',
        },
      ],
      documents: [
        {
          id: 'DOC-PHN-01',
          docType: 'CUSTOMS_DECLARATION',
          title: 'Customs Declaration D10-CAS-2023-44180',
          documentHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          hashAlgorithm: 'SHA-256',
          storageRef: 's3://wathiq-docs/customs/d10-cas-2023-44180.pdf',
          issuedBy: 'ADII Casablanca Port',
          issuedAt: '2023-10-14',
          sourceTrustLevel: 'OFFICIAL',
        },
      ],
      lastVerifiedAt: '2026-08-18 11:45:00',
    },
    grade: 'A',
    detailedGrading: {
      screen: 'A',
      body: 'A',
      keyboard: 'A',
      batteryScore: 'A',
      functionalScore: 'A',
      notes: 'No scratches on glass or camera lenses. Stainless steel band polished.',
    },
    status: 'READY_FOR_SALE',
    location: {
      warehouse: 'Casablanca Central Hub',
      zone: 'Zone B - Finished Goods',
      shelf: 'Tray 02',
      bin: 'Bin 05',
    },
    warranty: {
      durationMonths: 12,
      terms: '12 Months Express Replacement Mobile Warranty',
      certificateNumber: 'WTH-CERT-2026-00042',
    },
    diagnostics: {
      cpu: true,
      ram: true,
      ssd: true,
      gpu: true,
      display: true,
      keyboard: true,
      trackpad: true,
      webcam: true,
      mic: true,
      speakers: true,
      usb: true,
      hdmi: true,
      usbC: true,
      wifi: true,
      bluetooth: true,
      battery: true,
      thermals: true,
      operator: 'Karim Mansouri',
      timestamp: '2026-08-17 10:30:00',
      overallPass: true,
    },
    dataWipe: {
      software: 'PhoneCheck Erasure v4.8',
      version: '4.8.1',
      method: 'ADISA Certified / NIST 800-88 Mobile Purge',
      operator: 'Amina El Amrani',
      date: '2026-08-18 11:30:00',
      certificateRef: 'PHN-WTH-2026-0042-PURGE',
      result: 'PASSED',
      verificationHash: '439fa82110c4d8e8b093129841f3e1a0b5f8c8d89e40e2b694b7914e6629df21',
    },
    qaInspection: {
      inspector: 'Hamza Radi',
      date: '2026-08-18 11:40:00',
      overallResult: 'PASS',
      checklist: [
        { id: 'faceid', name: 'FaceID & Biometric Sensors Functional', passed: true, critical: true },
        { id: 'oled', name: 'Original Apple OLED TrueTone Display', passed: true, critical: true },
        { id: 'bat', name: 'Battery Health >= 85%', passed: true, critical: true },
      ],
    },
    repairs: [],
    photos: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
    ],
    ownership: 'Wathiq 1P Inventory',
    compliance: {
      wipedNIST80088: true,
      ceMarked: true,
      eWasteCompliant: true,
    },
    createdAt: '2026-08-16 15:40:00',
    updatedAt: '2026-08-18 11:45:00',
  },
  {
    id: 'WTH-26-LPT-000185',
    sku: 'APL-MBP-14-M1PRO-16-512',
    category: 'Laptop',
    brand: 'Apple',
    manufacturer: 'Apple Inc',
    model: 'MacBook Pro 14" (M1 Pro)',
    modelNumber: 'MKGP3LL/A',
    serialNumber: 'C02GK98NMD6R',
    macAddress: 'F0:18:98:23:44:B1',
    specs: {
      cpu: 'Apple M1 Pro (8-core CPU, 14-core GPU)',
      ram: '16GB Unified Memory',
      storage: '512GB Apple High-Speed SSD',
      display: '14.2" Liquid Retina XDR (3024x1964) ProMotion 120Hz',
      gpu: '14-Core Apple Neural/GPU',
      color: 'Space Gray',
      os: 'macOS Sequoia 15.1 Clean Install',
    },
    batteryHealth: 95,
    batteryCycles: 88,
    ssdHealth: 99,
    acquisitionSource: 'Corporate Trade-in - Majorel Africa Casablanca',
    acquisitionDate: '2026-08-15',
    costs: {
      acquisitionCost: 8200,
      transport: 150,
      customs: 0,
      certification: 150,
      parts: 0,
      labor: 180,
      packaging: 75,
      otherDirect: 50,
      landedCost: 8805,
      warrantyReserve: 440,
      paymentFees: 120,
      shippingSubsidy: 50,
      expectedReturns: 100,
      contributionMargin: 2385,
    },
    pricing: {
      minimumPrice: 10500,
      recommendedPrice: 11900,
      marketPrice: 13500,
      sellingPrice: 11900,
      currency: 'MAD',
      targetMarginPct: 26.0,
    },
    valuation: {
      acquisitionValue: 8200,
      landedCost: 8805,
      marketValue: 13500,
      tradeInValue: 9000,
      wholesaleValue: 10800,
      recommendedRetailPrice: 11900,
      expectedResidualValue12m: 8500,
      valuationBasis: 'Pristine anodized condition, low battery cycle count (88), Apple M1 Pro premium residual stability.',
      currency: 'MAD',
      updatedAt: '2026-08-17 11:20:00',
    },
    provenance: {
      countryOfOrigin: 'United States',
      importerIdentity: 'Apple Authorized Distribution',
      importStatus: 'VERIFIED',
      anrtHomologationStatus: 'VERIFIED',
      blacklistStatus: 'NO_MATCH_FOUND',
      financingLienStatus: 'NO_MATCH_FOUND',
      ownershipChainStatus: 'VERIFIED',
      overallTrustStatus: 'WATHIQ_VERIFIED',
      checks: [
        {
          id: 'CHK-MBP-01',
          checkType: 'IDENTITY_OEM',
          label: 'Apple GSX Check',
          sourceName: 'Apple GSX',
          sourceTrustLevel: 'OFFICIAL',
          requestedAt: '2026-08-15 14:15:00',
          completedAt: '2026-08-15 14:15:02',
          status: 'VERIFIED',
          resultSummary: 'Serial number verified. No MDM or iCloud locks.',
          confidence: 1.0,
          operatorOrSystem: 'Apple GSX',
        },
      ],
      documents: [],
      lastVerifiedAt: '2026-08-17 11:20:00',
    },
    grade: 'A+',
    detailedGrading: {
      screen: 'A+',
      body: 'A',
      keyboard: 'A+',
      batteryScore: 'A+',
      functionalScore: 'A+',
      notes: 'Immaculate condition. Factory anodized finish with no dings. TrueTone functional.',
    },
    status: 'CERTIFIED',
    location: {
      warehouse: 'Casablanca Central Hub',
      zone: 'Zone B - Finished Goods',
      shelf: 'Shelf 01',
      bin: 'Bin 04',
    },
    warranty: {
      durationMonths: 12,
      terms: '12 Months Express Replacement Hardware Warranty, Wathiq Care Apple Edition',
      certificateNumber: 'WTH-CERT-2026-08915',
    },
    diagnostics: {
      cpu: true,
      ram: true,
      ssd: true,
      gpu: true,
      display: true,
      keyboard: true,
      trackpad: true,
      webcam: true,
      mic: true,
      speakers: true,
      usb: true,
      hdmi: true,
      usbC: true,
      wifi: true,
      bluetooth: true,
      battery: true,
      thermals: true,
      operator: 'Tarik Bensouda',
      timestamp: '2026-08-16 11:15:00',
      overallPass: true,
    },
    dataWipe: {
      software: 'Apple Configurator 2 & DFU Clean Erase',
      version: '2.16',
      method: 'NIST 800-88 Cryptographic Hardware Wipe + MDM Unenrollment Confirmed',
      operator: 'Amina El Amrani',
      date: '2026-08-16 13:40:00',
      certificateRef: 'APL-WTH-2026-8915-MDM-CLR',
      result: 'PASSED',
      verificationHash: '8b7f14b60098df2467d022138a0f9de272186780362f1c07080cf7bc73b32034',
    },
    qaInspection: {
      inspector: 'Hamza Radi',
      date: '2026-08-17 10:00:00',
      overallResult: 'PASS',
      checklist: [
        { id: 'mdm', name: 'MDM & iCloud Activation Lock Removed', passed: true, critical: true },
        { id: 'truetone', name: 'TrueTone & TouchID Sensors Operational', passed: true, critical: true },
        { id: 'battery', name: 'Battery Health >= 90%', passed: true, critical: true },
        { id: 'liquid', name: 'Liquid contact indicators (LCI) pristine white', passed: true, critical: true },
      ],
    },
    repairs: [],
    photos: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    ],
    ownership: 'Wathiq 1P Inventory',
    compliance: {
      wipedNIST80088: true,
      ceMarked: true,
      eWasteCompliant: true,
    },
    createdAt: '2026-08-15 14:10:00',
    updatedAt: '2026-08-17 11:20:00',
  },
];

export const INITIAL_EVENTS: DeviceEvent[] = [
  {
    id: 'EVT-001',
    deviceId: 'WTH-26-LPT-000184',
    eventType: 'DeviceReceived',
    fromState: 'EXPECTED',
    toState: 'RECEIVED',
    operatorId: 'USR-WH-02',
    operatorName: 'Mohamed Tazi',
    role: 'WAREHOUSE',
    timestamp: '2026-08-12 09:30:00',
    notes: 'Inbounded from Bank of Africa ITAD batch manifest. Barcode scanned.',
  },
  {
    id: 'EVT-002',
    deviceId: 'WTH-26-LPT-000184',
    eventType: 'DiagnosticCompleted',
    fromState: 'RECEIVED',
    toState: 'DIAGNOSTICS',
    operatorId: 'USR-TC-01',
    operatorName: 'Tarik Bensouda',
    role: 'TECHNICIAN',
    timestamp: '2026-08-14 10:45:00',
    notes: 'Hardware diagnostics ran. Worn keyboard flagged for replacement.',
  },
  {
    id: 'EVT-003',
    deviceId: 'WTH-26-LPT-000184',
    eventType: 'DataWipeCompleted',
    fromState: 'DIAGNOSTICS',
    toState: 'DATA_WIPE',
    operatorId: 'USR-SEC-01',
    operatorName: 'Amina El Amrani',
    role: 'OPERATIONS_MANAGER',
    timestamp: '2026-08-14 14:20:00',
    notes: 'Blancco NIST 800-88 Purge 100% verified. Certificate generated.',
  },
  {
    id: 'EVT-004',
    deviceId: 'WTH-26-LPT-000184',
    eventType: 'RepairCompleted',
    fromState: 'DATA_WIPE',
    toState: 'REFURBISHMENT',
    operatorId: 'USR-TC-01',
    operatorName: 'Tarik Bensouda',
    role: 'TECHNICIAN',
    timestamp: '2026-08-15 16:00:00',
    notes: 'New FR/AR backlit keyboard installed. Thermals renewed with Arctic MX-4.',
  },
  {
    id: 'EVT-005',
    deviceId: 'WTH-26-LPT-000184',
    eventType: 'QAPassedAndCertified',
    fromState: 'QA',
    toState: 'CERTIFIED',
    operatorId: 'USR-QA-01',
    operatorName: 'Hamza Radi',
    role: 'QA',
    timestamp: '2026-08-16 16:30:00',
    notes: 'Full 17-point QA passed. Grade A certified. Public digital passport created.',
  },
  {
    id: 'EVT-006',
    deviceId: 'WTH-26-LPT-000184',
    eventType: 'StatusChanged',
    fromState: 'CERTIFIED',
    toState: 'READY_FOR_SALE',
    operatorId: 'USR-OPS-01',
    operatorName: 'Yassine Kabbaj',
    role: 'OPERATIONS_MANAGER',
    timestamp: '2026-08-16 17:00:00',
    notes: 'Priced at 5,900 MAD. Moved to Finished Goods Bin 14.',
  },
];

export const INITIAL_ACCOUNTS: B2BAccount[] = [
  {
    id: 'ACC-001',
    companyName: 'Webhelp Nearshore Morocco',
    industry: 'Business Process Outsourcing / Call Centers',
    employeeCount: 4500,
    fleetSize: 3200,
    procurementCycle: 'Quarterly Refresh (200-300 units/cycle)',
    currentSupplier: 'Direct OEM New (Lenovo / HP)',
    annualItSpend: 14500000,
    accountOwner: 'Sofia Mansouri (VP B2B Sales)',
    city: 'Casablanca (Nearshore Park)',
    taxId: 'ICE: 001594812000045',
    status: 'ACTIVE',
  },
  {
    id: 'ACC-002',
    companyName: 'Majorel Africa SA',
    industry: 'Customer Experience & CRM BPO',
    employeeCount: 3800,
    fleetSize: 2600,
    procurementCycle: 'Bi-Annual (150-250 units/cycle)',
    currentSupplier: 'Local Resellers',
    annualItSpend: 9800000,
    accountOwner: 'Sofia Mansouri',
    city: 'Casablanca & Rabat',
    taxId: 'ICE: 002148900000088',
    status: 'ACTIVE',
  },
  {
    id: 'ACC-003',
    companyName: 'Université Privée de Fès',
    industry: 'Higher Education & Computer Labs',
    employeeCount: 450,
    fleetSize: 650,
    procurementCycle: 'Annual Back-to-School (August-September)',
    currentSupplier: 'Tender / Public procurement',
    annualItSpend: 2800000,
    accountOwner: 'Omar Chraibi',
    city: 'Fez',
    taxId: 'ICE: 003849100000021',
    status: 'ACTIVE',
  },
  {
    id: 'ACC-004',
    companyName: 'MaroTech Managed IT Services',
    industry: 'Managed Service Provider (MSP)',
    employeeCount: 85,
    fleetSize: 380,
    procurementCycle: 'Continuous On-Demand (10-30 units/mo)',
    currentSupplier: 'Gray market / Uncertified brokers',
    annualItSpend: 1900000,
    accountOwner: 'Omar Chraibi',
    city: 'Tangier Med',
    taxId: 'ICE: 004928100000099',
    status: 'PROSPECT',
  },
];

export const INITIAL_CONTACTS: B2BContact[] = [
  {
    id: 'CON-001',
    accountId: 'ACC-001',
    name: 'Mehdi Bennani',
    role: 'Chief Information Officer (CIO)',
    email: 'm.bennani@webhelp.ma',
    phone: '+212 522 98 44 10',
    whatsApp: '+212 661 24 55 88',
  },
  {
    id: 'CON-002',
    accountId: 'ACC-001',
    name: 'Zineb Alami',
    role: 'Procurement Director',
    email: 'z.alami@webhelp.ma',
    phone: '+212 522 98 44 12',
    whatsApp: '+212 662 10 33 44',
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'OPP-001',
    accountId: 'ACC-001',
    accountName: 'Webhelp Nearshore Morocco',
    title: '150 × ThinkPad T14 Gen 2 Fleet Deployment',
    value: 718500,
    currency: 'MAD',
    stage: 'QUOTE',
    probability: 80,
    expectedClose: '2026-09-30',
    unitsRequested: 150,
    notes: 'Client evaluating quote. Requires customized French/Arabic keyboard and 12-month advance swap SLA.',
  },
];

export const INITIAL_QUOTES: B2BQuote[] = [
  {
    id: 'QT-2026-089',
    quoteNumber: 'WTH-QT-2026-089',
    accountId: 'ACC-001',
    clientName: 'Webhelp Nearshore Morocco',
    contactPerson: 'Mehdi Bennani (CIO)',
    email: 'm.bennani@webhelp.ma',
    items: [
      {
        id: 'QI-001',
        sku: 'LEN-T14-G2-I5-16-512',
        model: 'Lenovo ThinkPad T14 Gen 2 (i5 11th Gen / 16GB / 512GB SSD / Grade A)',
        grade: 'A',
        quantity: 100,
        unitPrice: 4790,
        totalPrice: 479000,
        warrantyMonths: 12,
      },
    ],
    deploymentFee: 15000,
    deliveryFee: 4500,
    subtotal: 563500,
    taxRate: 0.20,
    taxAmount: 112700,
    total: 676200,
    currency: 'MAD',
    status: 'SENT',
    createdAt: '2026-08-17',
    validUntil: '2026-09-17',
    notes: 'Includes 12-month Wathiq Morocco Hardware Care: 24h replacement guarantee.',
  },
];

export const INITIAL_ITAD_BATCHES: ITADBatch[] = [
  {
    id: 'ITAD-001',
    batchNumber: 'ITAD-CAS-2026-014',
    clientName: 'Bank of Africa Head Office Casablanca',
    city: 'Casablanca (Anfa Place)',
    deviceCount: 284,
    status: 'IN_PROCESSING',
    collectionDate: '2026-08-10',
    manifestNumber: 'MNF-BOA-2026-089',
    recoveryValuation: 890000,
    environmentalReductionCo2Kg: 42600,
    wipedCertCount: 210,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-2026-0412',
    orderNumber: 'WTH-ORD-2026-0412',
    customerName: 'Karim Tazi',
    customerEmail: 'k.tazi@outlook.com',
    customerPhone: '+212 661 33 22 11',
    customerType: 'B2C',
    items: [
      {
        deviceId: 'WTH-26-LPT-000184',
        model: 'Lenovo ThinkPad T14 Gen 2 (i5 / 16GB / 512GB)',
        price: 5900,
        grade: 'A',
        serialNumber: 'PF-2947A890',
      },
    ],
    subtotal: 5900,
    shipping: 50,
    total: 5950,
    currency: 'MAD',
    status: 'PAID',
    shippingAddress: 'Boulevard d’Anfa, Casablanca',
    city: 'Casablanca',
    paymentMethod: 'CREDIT_CARD',
    createdAt: '2026-08-18 14:20:00',
    trackingNumber: 'CTM-EXP-948102',
  },
];

export const INITIAL_WARRANTY_CLAIMS: WarrantyClaim[] = [
  {
    id: 'CLM-26-0042',
    claimNumber: 'WTH-CLM-26-0042',
    deviceId: 'WTH-26-LPT-000184',
    customerName: 'Karim Tazi',
    customerEmail: 'k.tazi@outlook.com',
    issueDescription: 'Customer reported spacebar intermittently double-spaces',
    status: 'OPEN',
    resolutionNotes: 'Arranging swap keyboard under Care Plan.',
    repairCost: 0,
    openedAt: '2026-08-18 16:30:00',
  },
];

export const INITIAL_RMA: RMAInspection[] = [
  {
    id: 'RMA-26-018',
    rmaNumber: 'WTH-RMA-26-018',
    deviceId: 'WTH-26-LPT-000184',
    customerName: 'Webhelp Morocco',
    reason: 'Intermittent Bluetooth disconnect',
    status: 'INSPECTED',
    inspectionResult: 'HARDWARE_FAULT',
    disposition: 'ROUTE_TO_REWORK',
    createdAt: '2026-08-17 14:00:00',
    updatedAt: '2026-08-18 09:30:00',
  },
];

export const INITIAL_MOVEMENTS: InventoryMovement[] = [
  {
    id: 'MOV-001',
    deviceId: 'WTH-26-LPT-000184',
    fromLocation: {
      warehouse: 'Casablanca Central Hub',
      zone: 'Dock Inbound',
      shelf: 'Bay 01',
      bin: 'Intake Pallet 04',
    },
    toLocation: {
      warehouse: 'Casablanca Central Hub',
      zone: 'Zone B - Finished Goods',
      shelf: 'Shelf 03',
      bin: 'Bin 14',
    },
    operator: 'Mohamed Tazi',
    timestamp: '2026-08-16 17:05:00',
    reason: 'Certification completed. Stocked for commercial fulfillment.',
  },
];
